= Quarkus - Logging Logback
:extension-status: preview

This extension allows you to use Logback to configure Quarkus logging via `logback.xml`. This extension parses the config
file at build time, and then bridges the resulting config with jboss-logmanager.

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.logging.logback:quarkus-logging-logback` extension first.
In your `pom.xml` file, add:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.logging.logback</groupId>
    <artifactId>quarkus-logging-logback</artifactId>
</dependency>
----

== Technical Details

This extension does not actually replace jboss-logmanager as the default logging engine, instead it bridges to the two,
to allow them to co-exist. JBoss Logging is still the core logmanager for Quarkus, however any logging events it receives
are also sent to the logback and will be sent through any logback appenders.

Log levels for loggers are also parsed, and are used to set the default log level for the corresponding jboss-logmanager
loggers. These defaults can still be overriden however, so if you set a log level in `application.properties` it will take
precidence.

If a console appender is detected in `logback.xml` then the standard Quarkus console logging is disabled, to prevent double
logging of messages, otherwise it is left enabled and will work as normal.